# Generated by Django 3.1.5 on 2021-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='amount',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
